### ISSUE TITLE
App store not loading

### ISSUE THREAD

**Issue by AutomateMyLifee** [runcitadel/core#74]
Everything else seems to be working normal, but my appstore is just blank. I installed following the ubuntu method on the website. I found the following in the log that I think may be related to the problem.

Karen logs
----------

This script must only be run on Citadel OS
Cloning into '/tmp/tmp0zrj5zgs'...
Cloning the repository
Traceback (most recent call last):
  File "/home/user/citadel/scripts/../app/app-manager.py", line 70, in <module>
    updateRepos()
  File "/home/user/citadel/app/lib/manage.py", line 354, in updateRepos
    "githubRepo": gitUrl.removeprefix("https://github.com/").removesuffix(".git").removesuffix("/"),
AttributeError: 'str' object has no attribute 'removeprefix'
This script must only be run on Citadel OS

**Comment by AutomateMyLifee** [comment]
It appears the issue was that I have python 3.8 and you need at least 3.9. I wasn't able to update my python on Ubuntu LTS so for those who may have the same situation, I modified line 354 in app/lib/manage.py from:

`"githubRepo": gitUrl.removeprefix("https://github.com/").removesuffix(".git").removesuffix("/"),`
to
`"githubRepo": gitUrl[18:],`
